import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Select, { components } from "react-select";
import { useState, useEffect } from "react";

//Components
import Control from "../public/components/control/control";
import Result from "../public/components/result/result";

//util
import {
  countries,
  travelCodes,
  customSelectStyles,
  makeCategories,
  makeCountryList,
} from "../public/util/util";

export default function Home({ data }) {
  const [chosenCountry, setChosenCountry] = useState(false);
  const [categories] = useState(
    data.config.colorAxis.dataClasses &&
      makeCategories(data.config.colorAxis.dataClasses)
  );
  const [countries] = useState(data.data[0].data && data.data[0].data);
  const [selectCountries] = useState(
    data.data[0] && makeCountryList(data.data[0].data)
  );

  const changeCountry = (country) => {
    setChosenCountry(country.value);
  };
  // console.log("categories", categories);
  // console.log("selectCountries", selectCountries);
  // console.log("chosenCountry", chosenCountry);
  return (
    <div className={styles.page}>
      <Head>
        <title>Kan jeg reise til...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["page__container"]}>
        <h1>{`Kan jeg reise til ${
          !chosenCountry ? "..." : chosenCountry + "?"
        }`}</h1>
        <div className={styles["page__search"]}>
          {!chosenCountry ? (
            <Select
              components={{ Control }}
              options={selectCountries}
              styles={customSelectStyles}
              value={chosenCountry}
              onChange={changeCountry}
              placeholder={"Velg et land..."}
              instanceId={"search"}
            />
          ) : (
            <Result
              chosenCountry={chosenCountry}
              setChosenCountry={setChosenCountry}
              countries={countries}
              categories={categories}
            />
          )}
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://www.fhi.no/api/chartdata/excel/series/96079"
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
